[colors]
ansi = [
  "#f8f4ed", # bg,      hanbaiyu
  "#c21f30", # red,     fengyehong
  "#12aa9c", # green,   meidielü
  "#806332", # yellow,  canghuang
  "#1661ab", # blue,    dianqing
  "#ee2c79", # magenta, zijinghong
  "#1e9eb3", # cyan,    cuilan
  "#47484c", # fg0,     waguanhui
]
background = "#f8f4ed" # bg, hanbaiyu
brights = [
  "#e4dfd7", # bg0,      zhenzhuhui
  "#f03752", # red0,     haitanghong
  "#57c3c2", # green0,   shilü
  "#fbb957", # yellow0,  mihuang
  "#66a9c9", # blue0,    jianshilan
  "#ea7293", # magenta0, fengxianhuahong
  "#51c4d3", # cyan0,    pubulan
  "#21373d", # fg,       huilan
]
compose_cursor = "#51c4d3" #  cyan0,  pubulan
cursor_bg = "#21373d" #       fg,     huilan
cursor_border = "#21373d" #   fg,     huilan
cursor_fg = "#f8f4ed" #       bg,     hanbaiyu
foreground = "#21373d" #      fg,     huilan
scrollbar_thumb = "#47484c" # fg0,    waguanhui
selection_bg = "#e4dfd7" #    bg0,    zhenzhuhui
selection_fg = "none"
split = "#47484c" #           fg0,    waguanhui

[colors.indexed]

[colors.tab_bar]
background = "#e4dfd7" # bg0, zhenzhuhui

[colors.tab_bar.active_tab]
bg_color = "#f8f4ed"  # bg, hanbaiyu
fg_color = "#21373d"  # fg, huilan
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#e4dfd7"  # bg0, zhenzhuhui
fg_color = "#47484c"  # fg0, waguanhui
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#47484c"  # fg0, waguanhui
fg_color = "#f8f4ed"  # bg,  hanbaiyu
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#e4dfd7"  # bg0, zhenzhuhui
fg_color = "#47484c"  # fg0, waguanhui
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#47484c"  # fg0, waguanhui
fg_color = "#f8f4ed"  # bg,  hanbaiyu
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
aliases = []
author = "Lettepa"
name = "Lettepa Light"
origin_url = "https://github.com/lettepa/wezterm"
